spring.application.name=bookstore_graphql_client

server.port=8090

# Database connection config
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstores?currentSchema=bookstore_api_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

bearer=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJIYXJkY292ZXIiLCJ2ZXJzaW9uIjoiOCIsImp0aSI6IjM2NGExZmU3LWE4MmMtNDAwNy1iZjQyLWJkMmZlMDU1YmEwMCIsImFwcGxpY2F0aW9uSWQiOjIsInN1YiI6IjMzMzk1IiwiYXVkIjoiMSIsImlkIjoiMzMzOTUiLCJsb2dnZWRJbiI6dHJ1ZSwiaWF0IjoxNzQ1MDkwMDE4LCJleHAiOjE3NzY2MjYwMTgsImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1yb2xlIjoidXNlciIsIlgtaGFzdXJhLXVzZXItaWQiOiIzMzM5NSJ9LCJ1c2VyIjp7ImlkIjozMzM5NX19.pbm7Yg_BVajfwZiDaJneRQgUp1Qia8Y6zGtcTL141LE